### ISSUE TITLE
😂 Is it fork Cicerone? 

### ISSUE THREAD

**Issue by terrakok** [hakobast/flowzard#1]
https://github.com/terrakok/Cicerone

**Comment by hakobast** [comment]
:D Hi @terrakok. I used routing part from Cicerone, but this is not fork of Cicerone. Sorry I forget write about Cicerone that helped me a lot. I will write about it and about you in README. Ah and of course will read about licenses, maybe I did something wrong. Thank you to you and sorry again for not mentioning you in this library.

**Comment by terrakok** [comment]
No problems 😎

**Comment by hakobast** [comment]
@terrakok Hey i just pushed updated README file. Please check.
